# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Nom')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Famille',
                'verbose_name_plural': 'Familles',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='public/uploads/snakes', verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Média',
                'verbose_name_plural': 'Médias',
            },
        ),
        migrations.CreateModel(
            name='Mutation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Snake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_m', models.CharField(max_length=256, verbose_name='Reproducteur')),
                ('parent_f', models.CharField(max_length=256, verbose_name='Reproductrice')),
                ('s_name', models.CharField(max_length=256, verbose_name='Nom scientifique')),
                ('c_name', models.CharField(max_length=256, verbose_name='Nom commun')),
                ('birthday', models.DateField(verbose_name='Né le')),
                ('sex', models.CharField(choices=[('M', 'Mâle'), ('F', 'Femelle'), ('D', 'Mâle et femelle'), ('I', 'Inconnu')], max_length=1, verbose_name='Sexe')),
                ('slug', models.SlugField()),
                ('captive_birth', models.BooleanField(verbose_name='NZ')),
                ('cites', models.BooleanField(verbose_name='Soumi au CITES')),
                ('for_sale', models.BooleanField(verbose_name='À vendre')),
                ('price_sale', models.FloatField(blank=True, verbose_name='Prix de vente')),
                ('price_cpl', models.FloatField(blank=True, verbose_name='Prix de couple')),
                ('flex_price', models.FloatField(blank=True, verbose_name='Prix à discuter')),
                ('old', models.BooleanField(verbose_name='Ancien serpent')),
                ('infos', models.TextField(blank=True, verbose_name='Informations complémentaires')),
                ('private_data', models.TextField(blank=True, verbose_name='Informations pour nous')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snake.Family', verbose_name='Famille')),
                ('mutation', models.ManyToManyField(to='snake.Mutation')),
            ],
            options={
                'verbose_name': 'Serpent',
                'verbose_name_plural': 'Nos serpents',
            },
        ),
        migrations.AddField(
            model_name='gallery',
            name='snake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snakes', related_query_name='snake', to='snake.Snake'),
        ),
    ]
