# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0006_auto_20170927_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snake',
            name='birthday',
            field=models.CharField(default='2017', max_length=10, verbose_name='Né en'),
        ),
        migrations.AlterField(
            model_name='snake',
            name='c_name',
            field=models.CharField(default='Python royal', max_length=256, verbose_name='Nom commun'),
        ),
        migrations.AlterField(
            model_name='snake',
            name='captive_birth',
            field=models.BooleanField(default=True, verbose_name='NZ'),
        ),
        migrations.AlterField(
            model_name='snake',
            name='cites',
            field=models.BooleanField(default=True, verbose_name='Soumi au CITES'),
        ),
        migrations.AlterField(
            model_name='snake',
            name='s_name',
            field=models.CharField(default='Python regius', max_length=256, verbose_name='Nom scientifique'),
        ),
        migrations.AlterField(
            model_name='snake',
            name='sex',
            field=models.CharField(choices=[('M', 'Mâle'), ('F', 'Femelle'), ('D', 'Mâle et femelle'), ('I', 'Inconnu')], default='M', max_length=1, verbose_name='Sexe'),
        ),
    ]
