# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_m', models.CharField(max_length=256, verbose_name='Reproducteur')),
                ('parent_f', models.CharField(max_length=256, verbose_name='Reproductrice')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField()),
                ('los_number', models.CharField(max_length=256, verbose_name='Numéro LOS')),
                ('sex', models.CharField(choices=[('M', 'Mâle'), ('F', 'Femelle'), ('I', 'Inconnu')], max_length=1, verbose_name='Sexe')),
                ('birthday', models.DateField(verbose_name='Né le')),
                ('for_sale', models.NullBooleanField(verbose_name='À vendre')),
                ('price_sale', models.FloatField(verbose_name='Prix de vente')),
                ('for_jut', models.NullBooleanField(verbose_name='Pour saillie')),
                ('jut_price', models.FloatField(verbose_name='Prix de la saillie')),
                ('previous_jut_birth', models.NullBooleanField(verbose_name="Né d'une précédente saillie")),
                ('informations', models.TextField(verbose_name='Informations complémentaire')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='public/uploads/cats', verbose_name='Nom')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', related_query_name='cat', to='cat.Cat')),
            ],
        ),
        migrations.AddField(
            model_name='cat',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cat.Color', verbose_name='Couleur'),
        ),
    ]
