# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cat',
            options={'verbose_name': 'Chat', 'verbose_name_plural': 'Chats'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Coloration', 'verbose_name_plural': 'Colorations'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Média', 'verbose_name_plural': 'Médias'},
        ),
        migrations.AlterField(
            model_name='cat',
            name='for_jut',
            field=models.BooleanField(default=False, verbose_name='Pour saillie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cat',
            name='for_sale',
            field=models.BooleanField(default=False, verbose_name='À vendre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cat',
            name='previous_jut_birth',
            field=models.BooleanField(default=False, verbose_name="Né d'une précédente saillie"),
            preserve_default=False,
        ),
    ]
