# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0002_auto_20170926_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='uploads/cats', verbose_name='Nom'),
        ),
    ]
