# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0003_auto_20170926_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='jut_price',
            field=models.FloatField(blank=True, verbose_name='Prix de la saillie'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='price_sale',
            field=models.FloatField(blank=True, verbose_name='Prix de vente'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', related_query_name='catsg', to='cat.Cat'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='cats', verbose_name='Nom'),
        ),
    ]
