# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0004_auto_20170927_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='birthday',
            field=models.CharField(max_length=10, verbose_name='Né le'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='price_sale',
            field=models.FloatField(blank=True, null=True, verbose_name='Prix de vente'),
        ),
    ]
